GET http://localhost:3000/collection1

###
GET http://localhost:3000/collection1/6518ca7833a84c0d8579825d

###
POST http://localhost:3000/collection1
content-type: application/json

{
    "ItemName": "Plates",
    "Department": "Paper",
    "Store": "Smiths",
    "City": "Houston",
    "Stock": "50",
    "Price": "6.00",
    "Aisle": "2"
}

###
POST http://localhost:3000/collection1
content-type: application/json

{
    "ItemName": "Plates 123512sx",
    "Department": "  ",
    "Store": "Smiths",
    "City": "Houston",
    "Stock": "Hello",
    "Price": "6.00AS",
    "Aisle": "2"
}
###
PUT http://localhost:3000/collection1/6518b63d33a84c0d8579825c HTTP/1.1
content-type: application/json

{
    "ItemName": "New_Mango",
    "Department": "Produce",
    "Store": "Walmart",
    "City": "NewYork",
    "Stock": "74",
    "Price": "5.00",
    "Aisle": "13"
}


####
 DELETE  http://localhost:3000/collection1/6518d941d9cb2f3ca597e4ca